Stage1
glebeckaya/jet-start pull request #1
Opened 2021-04-22 13:29 UTC by glebeckaya

2021-04-22 15:02 UTC, olimed reviewed
1) Отсутствие header на всех страницах
2) старайся называть localid более осмысленным
3) старайся писать код красиво, очень много длинных строк (тяжело смотреть)
4) добавь в header окна кнопку, чтобы можно было его закрыть

2021-04-22 15:02 UTC, olimed commented on sources/views/contacts.js
> +							return false;
зачем тебе здесь return?

2021-04-22 15:02 UTC, olimed commented on sources/views/contacts.js
> +						"wxi-trash": (e, id) => {
у тебя нет в листе такого класса. проверяй код. который ты пишешь, этот функционал не используется

2021-04-22 15:02 UTC, olimed commented on sources/views/contacts.js
> +						template: `<div class='webix_icon wxi-user'></div>
лучше использовать заглушку, если нет аватарки, то сетить какую-то дефолтную картинку

2021-04-22 15:02 UTC, olimed commented on sources/views/contacts.js
> +		this.on(this.list, "onAfterSelect", id => this.setParam("id", id, true));
можно эти собфтия прописывать в конфиге листа

2021-04-22 15:02 UTC, olimed commented on sources/views/contacts.js
> +			const currentId = (contacts.exists(id)) ? id : contacts.getFirstId();
лишние скобки

2021-04-22 15:02 UTC, olimed commented on sources/views/contactsInfo.js
> +					<div><div class='photo'></div><p>Status: #status#</p></div>
можно использовать какую-нибудь картинку по дефолту

2021-04-22 15:02 UTC, olimed commented on sources/views/contactsInfo.js
> +			}
логичнее засетить существующую айдишку, если такой в урле нет или неверная айдишка

2021-04-22 15:02 UTC, olimed commented on sources/views/activities.js
> +			this.addForm = this.ui(new PopupView(this.app, "Add", "Add", activities, activitytypes, contacts));
1) можно создать один попап и показывать его по клику на разных кнопках, а в классе с попапом можешь добавить методы, где будешь менять текст кнопок и сетить данные
2) передача коллекций - хорошо, но когда у тебя их будет 1000. то слишком много аргументов придеться создавать. поэтому лучше вынеси в отдельный объект их и передавай его

2021-04-22 15:02 UTC, olimed commented on sources/views/windows/popup.js
> +			view: "window",
лучше делать модальным окном, а то пользователь может удалить запись пока ты ее редактируешь

2021-04-22 15:02 UTC, olimed commented on sources/views/windows/popup.js
> +							body: {template: "#Value#"}
почему 2 темплайта?

2021-04-22 15:02 UTC, olimed commented on sources/views/windows/popup.js
> +		values.DueDate = `${values.date.split(" ")[0]} ${values.time}`;
лучше переделать на webix.Date.dateToStr и в datepicker возвращать дату, а не строку. Ты не можешь быть уверенна, что в следующем релизе вебикса разделитель останеться пробел, а не другой символ

2021-04-22 15:02 UTC, olimed commented on sources/views/activities.js
> +								return " ";
кажется, эта проверка не нужна

2021-04-23 01:11 UTC, glebeckaya commented on sources/views/activities.js
> +								return " ";
удалила проверку

2021-04-23 01:11 UTC, glebeckaya commented on sources/views/windows/popup.js
> +		values.DueDate = `${values.date.split(" ")[0]} ${values.time}`;
заменила на webix.Date.dateToStr

2021-04-23 01:11 UTC, glebeckaya commented on sources/views/windows/popup.js
> +							body: {template: "#Value#"}
убрала suggest, в котором были template, заменила на options

2021-04-23 01:11 UTC, glebeckaya commented on sources/views/windows/popup.js
> +			view: "window",
добавила modal: true в конфиг

2021-04-23 01:11 UTC, glebeckaya commented on sources/views/activities.js
> +			this.addForm = this.ui(new PopupView(this.app, "Add", "Add", activities, activitytypes, contacts));
переписала на один попап

2021-04-23 01:12 UTC, glebeckaya commented on sources/views/contactsInfo.js
> +			}
логика при вводе несуществующей id прописана в contacts.js на листе, поэтому подразумевается, что id всегда корректная. нужно повторять ее и здесь?

2021-04-23 01:12 UTC, glebeckaya commented on sources/views/contactsInfo.js
> +					<div><div class='photo'></div><p>Status: #status#</p></div>
применила дефолтную картинку

2021-04-23 01:12 UTC, glebeckaya commented on sources/views/contacts.js
> +			const currentId = (contacts.exists(id)) ? id : contacts.getFirstId();
удалила

2021-04-23 01:12 UTC, glebeckaya commented on sources/views/contacts.js
> +		this.on(this.list, "onAfterSelect", id => this.setParam("id", id, true));
повесила обработку события onAfterSelect в конфиге list

2021-04-23 01:12 UTC, glebeckaya commented on sources/views/contacts.js
> +						template: `<div class='webix_icon wxi-user'></div>
поставила дефолтную картинку, если у объекта пустой ключ "Photo"

2021-04-23 01:12 UTC, glebeckaya commented on sources/views/contacts.js
> +						"wxi-trash": (e, id) => {
извиняюсь, удалила

2021-04-23 01:12 UTC, glebeckaya commented on sources/views/contacts.js
> +							return false;
убрала эту часть, ненужная логика

2021-04-23 07:24 UTC, olimed commented on sources/views/activities.js
> +							},
в данном случае можешь не использовать template, так как в коллекции есть поле value

2021-04-23 07:24 UTC, olimed commented on sources/views/activities.js
> +							},
смотри комментарий выше

2021-04-23 07:24 UTC, olimed commented on sources/views/contactsInfo.js
> +			}
нет, проверку еще одну не нужно, но желательно подстраховаться, чтобы не было ситуаций как на картинке
![image](https://user-images.githubusercontent.com/31127246/115834381-d89b5f00-a41d-11eb-83f6-0e03ece49669.png)

2021-04-23 08:04 UTC, glebeckaya commented on sources/views/activities.js
> +							},
удалила template

2021-04-23 08:04 UTC, glebeckaya commented on sources/views/activities.js
> +							},
удалила template

2021-04-23 08:04 UTC, glebeckaya commented on sources/views/contactsInfo.js
> +			}
исправила, показываю пустые строки, если нет контактов

2021-04-23 12:37 UTC, HelgaListopad requested changes
Линтер ругается на linebreak-style

2021-04-23 12:37 UTC, HelgaListopad commented on sources/views/activities.js
> +			this._jetPopup = this.ui(PopupView);
Этот попап на ините зависит от промиса? 
Если нет, то можно вынести выше

2021-04-23 12:37 UTC, HelgaListopad commented on sources/models/activities.js
> +			let parserTime = webix.Date.strToDate("%H:%i");
$init/$change срабатывает для каждой отдельной записи - каждый раз инитить один и тот же парсер не очень продуктивно. `parserDate` и `parserTime` можно вынести из activities как константы, и просто использовать их в обоих меотдах

2021-04-23 12:37 UTC, HelgaListopad commented on sources/views/windows/popup.js
> +			move: true,
Я бы убрала отсюда `move`, так как это свойство приведёт к сбросу `position:"center"`, как только пользователь пошевелит окно (будет выставлена позиция, в которую его перетащили). 
И раз окно переиспользуется и прячется (как и должно быть), то при следующем открытии оно будет на той позиции, которую выставили последней. 
Оставлять `move` и центрировать его каждый раз перед открытием возможно, но это лишнее.

2021-04-23 13:30 UTC, glebeckaya commented on sources/views/windows/popup.js
> +			move: true,
убрала move

2021-04-23 13:31 UTC, glebeckaya commented on sources/models/activities.js
> +			let parserTime = webix.Date.strToDate("%H:%i");
вынесла parser в переменную

2021-04-23 13:31 UTC, glebeckaya commented on sources/views/activities.js
> +			this._jetPopup = this.ui(PopupView);
убрала промис вообще, здесь он не нужен

2021-04-23 13:32 UTC, glebeckaya commented
> Линтер ругается на linebreak-style

у меня линтер проходит без ошибок

2021-04-23 13:32 UTC, olimed commented on sources/models/activities.js
> +			let parser = webix.Date.strToDate("%Y-%m-%d %H:%i");
лучше парсер вынести до создания коллекции, так нет смысла их каждый раз создавать

2021-04-23 13:32 UTC, olimed commented on sources/views/windows/popup.js
> +		if (this.values) this.form.setValues(this.values);
альтернатива твоему способу, чтобы лишний раз не обращаться к коллекции, ты можешь просто проверять на наличие id в аргументах:
if (id) {
this.values = activities.getItem(id);
this.form.setValues(this.values || {});
}

2021-04-23 13:32 UTC, olimed commented on sources/views/windows/popup.js
> +		let parserTime = webix.Date.dateToStr("%H:%i");
можешь вынести за класс и создать их как константы

2021-04-23 13:44 UTC, glebeckaya commented on sources/views/windows/popup.js
> +		if (this.values) this.form.setValues(this.values);
переписала на наличие приходящего id

2021-04-23 13:44 UTC, glebeckaya commented on sources/models/activities.js
> +			let parser = webix.Date.strToDate("%Y-%m-%d %H:%i");
вынесла парсер

2021-04-23 13:44 UTC, glebeckaya commented on sources/views/windows/popup.js
> +		let parserTime = webix.Date.dateToStr("%H:%i");
вынесла в константы

2021-04-23 13:47 UTC, olimed approved these changes

2021-04-23 13:52 UTC, HelgaListopad approved these changes

2021-04-23 13:52 UTC, merged