Stage2
glebeckaya/jet-start pull request #2
Opened 2021-04-27 15:54 UTC by glebeckaya

2021-04-27 16:29 UTC, olimed reviewed
1) фильтр активити не работает после добавления записи

2021-04-27 16:29 UTC, olimed commented on sources/views/contactsForm.js
> +															reader.readAsDataURL(file);
если тебе не нужно дальнейшая обработка файла, то в onBeforeFileAdd желательно возвращать false

2021-04-27 16:29 UTC, olimed commented on sources/views/contactsForm.js
> +		]).then(() => {
загрузку коллекций лучше вынести в init

2021-04-27 16:29 UTC, olimed commented on sources/views/contactsForm.js
> +		});
так как код посторяющийся, то можно вынести в функцию и передаваь только лэйблы. которые нужно поменят

2021-04-27 16:29 UTC, olimed commented on sources/views/contactsForm.js
> +		}
можжно сделать по-другому. чтобы не копировать код:
``contacts.waitSave(() => {
   if (values.id) {
      contacts.updateItem(values.id, values);
} else contacts.add(values);
			}).then(() => {
				this.cancelContactForm();
			});``

2021-04-28 07:42 UTC, olimed commented on sources/views/contacts.js
> +			if (this.getSubView().getUrlString() === "contactsForm") {
так как ты несколько раз берешь значение this.getSubView().getUrlString(), то лучше вынести в отдельную переменную

2021-04-28 07:42 UTC, olimed commented on sources/views/contacts.js
> +				if (currentId) {
эти условия можно объединить

2021-04-28 07:42 UTC, olimed commented on sources/views/contactsInfo.js
> +			});
здесь можно использовать метод dataCollection find:
https://docs.webix.com/api__link__datacollection_find.html

2021-04-28 07:42 UTC, olimed commented on sources/views/contactsInfo.js
> +			});
смотри коммент выше

2021-04-28 07:42 UTC, olimed commented on sources/views/windows/popup.js
> +	showWindow(readonly, title, buttonName, id) {
1) так как параметр readonly у тебя имеет тип boolean и по коду видно, то его можно передавать последним в списке и дефолтное значение выставить в false
2) здесь лучше все аргументы передавать в виде объекта:
вызов: ``showWindow({readonly: false, title: "title", buttonName: "name", id: 1})``
код: ``showWindow(options)``

2021-04-28 07:42 UTC, olimed commented on sources/views/windows/popup.js
>  			activities.waitSave(() => {
этот if можно заменить следующим образом:
``
activities.waitSave(() => {
    if (values.id) activities.updateItem(values.id, values);
    else activities.add(values);
}).then(() => {
    this.hideWindow();
});
``

2021-04-28 07:42 UTC, olimed commented on sources/views/windows/popup.js
> +			this.form.setValues({ContactID: contacts.getItem(contact)} || {});
при такой проверке у тебя никогда не выполнится второй сценарий. в лучшем случае у тебя будет {ContactID: undefined}, в худшем - ошибка ( если contacts не будут определены)

2021-04-28 07:42 UTC, olimed commented on sources/views/contactsTable.js
> +				files.filter(obj => obj.contact * 1 === this.id * 1);
1) каждый раз преобразовывать  this.id в число не ок, лучше вынести до фильтров
2) преобразовывать в число можно использовать: + (перед строкой)/parseInt/parsefloat
3) можно не преобразовывать каждый раз в число, можно сравнивать строки, а числа преобразовывать с помощию toString()

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contactsTable.js
> +				files.filter(obj => obj.contact * 1 === this.id * 1);
вынесла преобразование this.id (применила parseInt) в число до фильтрации

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/windows/popup.js
> +			this.form.setValues({ContactID: contacts.getItem(contact)} || {});
убрала пустой объект

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/windows/popup.js
>  			activities.waitSave(() => {
переписала

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/windows/popup.js
> +	showWindow(readonly, title, buttonName, id) {
переписала, передаю параметры в виде объекта

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contactsInfo.js
> +			});
переписала

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contactsInfo.js
> +			});
переписала с через collection.find

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contacts.js
> +				if (currentId) {
объединила условия

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contacts.js
> +			if (this.getSubView().getUrlString() === "contactsForm") {
вынесла в переменную this.getSubView(), немного переписала условия

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contactsForm.js
> +		}
переписала без повторяющегося кода

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contactsForm.js
> +		});
вынесла в отдельную функцию

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contactsForm.js
> +		]).then(() => {
убрала waitData, не влияет на работу кода

2021-04-28 09:27 UTC, glebeckaya commented on sources/views/contactsForm.js
> +															reader.readAsDataURL(file);
добавила return false

2021-04-28 09:54 UTC, olimed commented on sources/views/contacts.js
> +			if ((!subView && currentId) || (subView.getUrlString() === "contactsInfo" && currentId)) {
почему 2 раза проверяешь на наличие currentId?

2021-04-28 09:54 UTC, olimed commented on sources/views/contacts.js
> +			if (subView.getUrlString() === "contactsForm") this.list.unselectAll();
subView.getUrlString()  вынеси лучше в отдельную переменную

2021-04-28 09:54 UTC, olimed commented on sources/views/contactsForm.js
> +			this.photoTemplate.setValues(contacts.getItem(this.id));
contacts.getItem(this.id) выноси лучше в отдельные переменные, если ты используешь это несколько раз

2021-04-28 13:13 UTC, glebeckaya commented on sources/views/contactsForm.js
> +			this.photoTemplate.setValues(contacts.getItem(this.id));
вынесла в переменную

2021-04-28 13:13 UTC, glebeckaya commented on sources/views/contacts.js
> +			if (subView.getUrlString() === "contactsForm") this.list.unselectAll();
вынесла в переменную

2021-04-28 13:13 UTC, glebeckaya commented on sources/views/contacts.js
> +			if ((!subView && currentId) || (subView.getUrlString() === "contactsInfo" && currentId)) {
переписала

2021-04-29 07:10 UTC, olimed approved these changes

2021-04-30 07:18 UTC, HelgaListopad requested changes

2021-04-30 07:18 UTC, HelgaListopad commented on sources/views/contactsForm.js
> +			this.show(`/top/contacts?id=${id}/contactsInfo`);
Навигация от /top делает твоё приложение не очень гибким. 
Работает это сейчас хорошо, но если поменяестя уровень вложенности вьюшек, захардкоженные URLы придётся везде выискивать менять. 
У тебя такая навигация есть в трёх местах (два тут и один в темплейте) - попробуй связать эти вьюшки через события.
Что я имею в виду:
- отсюда и из Template вместо show ты вызываешь app-level событие с айдишкой нужного контакта в параметрах
- в Contacts view слушаешь это событие и просто вызываешь там setParam или show с относительным путём

2021-04-30 07:34 UTC, HelgaListopad commented
Не заметила сразу, но есть небольшой баг
- выбери контакт
- отфильтруй его activities 
- выбери другой контакт - фильтры не сбросятся/не будут применены для новых данных

2021-04-30 08:00 UTC, glebeckaya commented on sources/views/contactsForm.js
> +			this.show(`/top/contacts?id=${id}/contactsInfo`);
исправила

2021-04-30 08:02 UTC, glebeckaya commented
> Не заметила сразу, но есть небольшой баг
> 
> * выбери контакт
> * отфильтруй его activities
> * выбери другой контакт - фильтры не сбросятся/не будут применены для новых данных

исправила, очищаю фильтры при переключении

2021-04-30 08:06 UTC, HelgaListopad approved these changes

2021-04-30 08:11 UTC, merged