Stage3
glebeckaya/jet-start pull request #3
Opened 2021-05-03 23:07 UTC by glebeckaya

2021-05-04 07:27 UTC, olimed reviewed
1)  фильтр не сбрасывается при переключении между страницами в левом меню (если данные отфильтровать, а затем перейти на страницу Activities и снова перейти на страницу Contacts, то поле фильтра будет пустое, но показанны отфильтрованые данные. которые были в начале)

2021-05-04 07:27 UTC, olimed commented on sources/views/activities.js
> +	}
лучше вынести в метод ready, чтобы каждый раз при изменении url не происходила синхронизация

2021-05-04 07:27 UTC, olimed commented on sources/views/activities.js
> +		this.tableActivity.queryView({view: "datatable"}).setState(state);
this.tableActivity.queryView({view: "datatable"}) очень не стабильная вещь, но так как ты используешь localId, то ты можешь получить эту вьюшку с помощью this.$$("tableActivity"). Чтобы точно быть уверенной, что  localId  у тебя не поменяется, то лучше вынести ее в отдельную переменную и потом импортировать в этот модуль
( этот комментарий относится ко всем использованием this.tableActivity.queryView({view: "datatable"})  в этом файле)

2021-05-04 07:27 UTC, olimed commented on sources/views/contactsTable.js
> +				this.activitiesTable.queryView({view: "datatable"}).sync(activities);
смотри коммент про this.tableActivity.queryView({view: "datatable"})

2021-05-04 11:15 UTC, glebeckaya commented on sources/views/contactsTable.js
> +				this.activitiesTable.queryView({view: "datatable"}).sync(activities);
переписала, использую localId

2021-05-04 11:15 UTC, glebeckaya commented on sources/views/activities.js
> +		this.tableActivity.queryView({view: "datatable"}).setState(state);
переписала, использую localId

2021-05-04 11:15 UTC, glebeckaya commented on sources/views/activities.js
> +	}
вынесла в ready

2021-05-05 07:39 UTC, olimed commented on sources/views/activityTableView.js
> +									${activitytypes.getItem(obj.id) ? activitytypes.getItem(obj.id).Value : ""}`
${activitytypes.getItem(obj.id) лучше вынести в отдельную переменную, так как она используется несколько раз

2021-05-05 07:39 UTC, olimed commented on sources/views/activityTableView.js
> +						${activitytypes.getItem(obj.TypeID) ? activitytypes.getItem(obj.TypeID).Value : "default"}`,
${activitytypes.getItem(obj.TypeID) лучше вынести в отдельную переменную, так как она используется несколько раз

2021-05-05 07:39 UTC, olimed commented on sources/views/activities.js
> +		this.tableActivity.queryView({localId: tableLocalID}).registerFilter(
лучше вынеси в отдельный метод

2021-05-05 10:29 UTC, glebeckaya commented on sources/views/activities.js
> +		this.tableActivity.queryView({localId: tableLocalID}).registerFilter(
вынесла в отдельный метод

2021-05-05 10:29 UTC, glebeckaya commented on sources/views/activityTableView.js
> +						${activitytypes.getItem(obj.TypeID) ? activitytypes.getItem(obj.TypeID).Value : "default"}`,
вынесла в отдельную переменную

2021-05-05 10:29 UTC, glebeckaya commented on sources/views/activityTableView.js
> +									${activitytypes.getItem(obj.id) ? activitytypes.getItem(obj.id).Value : ""}`
вынесла в отдельную переменную

2021-05-05 10:47 UTC, olimed commented on sources/views/contactsTable.js
> +				this.activitiesTable.queryView({localId: tableLocalID}).sync(activities);
так как this.activitiesTable.queryView({localId: tableLocalID}) используешь несколько раз, то лучше вынести в отдельную переменную

2021-05-05 10:50 UTC, glebeckaya commented
> 1. фильтр не сбрасывается при переключении между страницами в левом меню (если данные отфильтровать, а затем перейти на страницу Activities и снова перейти на страницу Contacts, то поле фильтра будет пустое, но показанны отфильтрованые данные. которые были в начале)

исправила

2021-05-05 10:59 UTC, glebeckaya commented on sources/views/contactsTable.js
> +				this.activitiesTable.queryView({localId: tableLocalID}).sync(activities);
вынесла отдельно

2021-05-05 11:00 UTC, olimed approved these changes

2021-05-05 16:54 UTC, HelgaListopad requested changes

2021-05-05 16:54 UTC, HelgaListopad commented on sources/views/activities.js
> +						const todayDay = {start: today, end: new Date(year, month, dayOfMonth + 1)};
start здесь будет не с начала дня, а с времени, которое попадает в new Date()
Хорошо бы с самого начала сбросить время для today через setHours

2021-05-05 16:54 UTC, HelgaListopad commented on sources/views/activityTableView.js
> +									width: 500,
Я бы предложила сделать его поуже (уменьшить ширину карточек)
В Settings с datasuggest для эдитора у тебя всё аккуратнее выглядит

2021-05-05 17:21 UTC, glebeckaya commented on sources/views/activities.js
> +						const todayDay = {start: today, end: new Date(year, month, dayOfMonth + 1)};
изменила время для today

2021-05-05 17:21 UTC, glebeckaya commented on sources/views/activityTableView.js
> +									width: 500,
изменила размеры и вид карточек

2021-05-06 08:21 UTC, HelgaListopad approved these changes

2021-05-06 08:27 UTC, merged